apiVersion: v1
kind: Service 
metadata:
  name: immich-loadbalancer
  namespace: immich 
spec:
  type: LoadBalancer 
  selector:
    app: immich-server 
  ports:
    - name: http
      port: 80
      targetPort: 2283
      protocol: TCP
