---

- name: Install Docker and dependencies
  hosts: all
  become: true
  tasks:
    
    - name: Add Docker repository
      ansible.builtin.command: "dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker Engine, Compose, BuildX, Python-docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - python3-docker
        state: "present"
        update_cache: true
        
    - name: Enable and start Docker Engine
      ansible.builtin.service:
        name: docker 
        enabled: true
        state: started

    - name: Enable and start containerd 
      ansible.builtin.service:
        name: containerd
        enabled: true
        state: started

    - name: Add Jenkins user to docker group
      ansible.builtin.user:
        name: jenkins
        groups: docker 
        append: true

    
- name: Initialize Swarm cluster
  hosts: swarm_manager
  become: true
  tasks:
    
    - name: Configure firewall ports for Swarm manager
      ansible.posix.firewalld:
        port: "{{ item.port }}/{{ item.protocol }}"
        permanent: true
        immediate: true
        state: enabled 
      loop:
        - { port: 2377, protocol: tcp }
        - { port: 7946, protocol: tcp }
        - { port: 7946, protocol: udp }
        - { port: 4789, protocol: udp }

    - name: Initialize Swarm
      community.docker.docker_swarm:
        state: "present"
        advertise_addr: "{{ ansible_host }}"
        listen_addr: "0.0.0.0"
      register: swarm_manager_output

    - name: Drain Swarm Manager node
      community.docker.docker_node: 
        hostname: "{{ ansible_facts['hostname'] }}"
        availability: "drain"


- name: Join worker nodes to cluster
  hosts: swarm_workers
  become: true
  tasks:

    - name: Join worker node to cluster 
      community.docker.docker_swarm: 
        state: join
        join_token: "{{ hostvars[groups['swarm_manager'][0]].swarm_manager_output.swarm_facts.JoinTokens.Worker }}"
        advertise_addr: "{{ ansible_host }}"
        remote_addrs:
          - "{{ groups['swarm_manager'][0] }}"

