Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos9s"

  config.vm.define "jenkins-1" do |jenkins1|
    jenkins1.vm.hostname = "jenkins-1"
    jenkins1.vm.network "private_network", ip: "192.168.56.101"

    jenkins1.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 3072
    end

    jenkins1.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    jenkins1.vm.provision "shell", path: "provisioners/create-ansible-user.sh"
    jenkins1.vm.provision "shell", path: "provisioners/create-jenkins-user.sh"
    jenkins1.vm.provision "shell", inline: "rm -f /tmp/id_ed25519.pub"
  end

  config.vm.define "jenkins-2" do |jenkins2|
    jenkins2.vm.hostname = "jenkins-2"
    jenkins2.vm.network "private_network", ip: "192.168.56.102"

    jenkins2.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 3072
    end

    jenkins2.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    jenkins2.vm.provision "shell", path: "provisioners/create-ansible-user.sh"
    jenkins2.vm.provision "shell", path: "provisioners/create-jenkins-user.sh"
    jenkins2.vm.provision "shell", inline: "rm -f /tmp/id_ed25519.pub"
  end
end