Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos9s"

  config.vm.define "swarm_master", primary: true do |master|
    master.vm.hostname = "swarm-master"
    master.vm.network "private_network", ip: "192.168.56.99"
    
    master.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 2048
    end
    
    master.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    master.vm.provision "shell", path: "provisioners/create-ansible-user.sh"
    master.vm.provision "shell", path: "provisioners/create-jenkins-user.sh"
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "swarm-worker1"
    worker1.vm.network "private_network", ip: "192.168.56.101"

    worker1.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 3072
    end

    worker1.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    worker1.vm.provision "shell", path: "provisioners/create-ansible-user.sh"
    worker1.vm.provision "shell", path: "provisioners/create-jenkins-user.sh"
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "swarm-worker2"
    worker2.vm.network "private_network", ip: "192.168.56.102"

    worker2.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 3072
    end

    worker2.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    worker2.vm.provision "shell", path: "provisioners/create-ansible-user.sh"
    worker2.vm.provision "shell", path: "provisioners/create-jenkins-user.sh"
  end
end