---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgCOC1u68XSJSYt4biUHknNLh9r32nDQGLNCZ0tQgU/ekBNfRL9gEc5B2chXGjP0vJkI/KruJDIiE+rJmrzESEM1JJiVKt+/eWJse7BKiEq//7plIhO+r2fI/kUgfichlN9bVpSX8j1Yo1mRu301nxfKc+Z9THW6KJBzIFp9tKBthkBRFqC6ZybN0tkX3By5utrQIiYJgngmJzI3gB3ePe0ehLCbXz1cFfh3mz7podO0r3eZR6Nj9vPPHIZyhqQ36VO1wOrwT9FoqCM3v18q7XA5eBRp+mKJhw09EgrmntO1abKb8tV9JSiL6EIrmGokddAJMG7HbrMbnFTLQd0yS4XCGX4KCE7AJH9dXHoTbHai5SLX9VtFOqR+sGUgZgvimwIHRaXwDdKwFfleTqJMoMTYe+Tr4+ru5uj561IEIbWuiagfBEF3c528ZcRPqcTmNiFsfL0rW0wyKY7WzEwmNugGPEmFHk4h1j2FHlVvh7dl8H8xmQk/PKKPzHZzbBQrCANVdSA73pvz/4fNu+cnY9jRRGVmArC10TVltdTI/wRuMViTCFQ2ezzRU7SIsqPPK7okstSY/A5NgniDHFiLAkx4oOI10iy5g5Y3Xqz4BN41dNLLwEN3w0Fuq3hPYjVR/yNyrCit0cpfyiAxwHDc015TFW0P6Kc9dbxsrhqA4AqerUF2mxyGc0iyamW/YWubGzEpF/QXdtQZeA==
  template:
    metadata:
      creationTimestamp: null
      name: immich-secret
      namespace: immich
    type: Opaque
