apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc 
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: linode-block-storage-retain

